name: ASCII name generator
on: 
  push:
    paths:
    - '.github/workflows/first.yaml'
jobs:
  ascii-job:
    name: this ascii first job
    runs-on: ubuntu-24.04
    steps:
    - name: checkout the repo
      uses: actions/checkout@v4
    - name: install ascii with shellscript
      run: |
        ls
        chmod +x ./ascii-code.sh
        ./ascii-code.sh
       
     
        
      
    
  
